services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      - TZ=Europe/Berlin
      - N8N_SECURE_COOKIE=false

    volumes:
      - n8n_data:/home/node/.n8n

    networks:
      - m1net

volumes:
  n8n_data:

networks:
  m1net:
    external: true
